### ISSUE TITLE
Name your url views!

### ISSUE THREAD

**Issue by nickcannariato** [KBiz65/kevinbisner-com#13]
This one matters way more when you start building larger and more complex Django projects, but it's a _really_ good habit to get into. 

When you define a `path` or `include` in any `urls.py` file, you have the option of _naming_ the view by passing it a "name=" key word argument.

The reason you'd want to do this is because there are many times you may want to change your URL structure or redirect a user from one part of your application to another. If you don't have named views, you have to rely on the URL path. 

Why wouldn't you want to do that? Well, lets take a look at this example.

In your site's root `urls.py` file (the one that's by the `settings.py` file in the `kbsite` directory) we updated our urls in #6 to look like this: 

```python
urlpatterns = [
    path('', include('home.urls')), 
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls), 
]
```

Let's say that somewhere in your `home` app, you have a page that you want to redirect to your blog. So you use [Django's built-in redirect function](https://docs.djangoproject.com/en/3.0/topics/http/shoftcuts/#redirect) to send the user to the relative url `blog/`.

Everything works and you're happy.

Now let's say that a few months from now, you decide that you want to change the URL to your blog. So you open up `kbsite/urls.py` and you change the `path` to `"thoughts/"` like so:

```python
urlpatterns = [
    path('', include('home.urls')), 
    path('thoughts/', include('blog.urls')),
    path('admin/', admin.site.urls), 
]
```

Now your blog app is at the `thoughts/` path in your application, and everything is working like you want.

Except you totally forgot about that hardcoded redirect! Now some user is going to click the link that sends them to `blog/` and get a 404, no page there.

This is, obviously, a fairly simple and silly example, but imagine your application has _hundreds_ or redirects (which would be incredibly common). You'd definitely forget one eventually, and you'd have to go through every template searching for where you did it to make sure that you could fix the bug.

## How could naming our views fix this?

If you read the documentation on that `redirect` function above, you can see that it can take one of three things:

- A model: the model’s get_absolute_url() function will be called.
- A view name, possibly with arguments: reverse() will be used to reverse-resolve the name.
- An absolute or relative URL, which will be used as-is for the redirect location.

We saw what happens when you use the relative url (`blog/` in our example above), and the model is a little out of scope for right now / I don't see that used very often in my experience. 

That middle one though, a view name, that's what we're looking for.

Let's adjust our original `kbsite/urls.py` file again and add names to our views:

```python
urlpatterns = [
    path('', include('home.urls'), name="home"), 
    path('blog/', include('blog.urls'), name="blog"),
    # The admin views are managed by Django, and all have their own names
    # already, so you'll want to leave this one alone
    path('admin/', admin.site.urls), 
]
```

Let's also add names to our `blog/urls.py` (or at least, the one we wound up with in issue #12:

```python
urlpatterns = [
    path('', PostList.as_view(), name="posts"),
]
```

Now, just like before, if we wanted to redirect a user somewhere in our application to our list of blog posts, we would pass the `redirect` function the specific name of our view like so:

```python
redirect('blog:posts)'
```

☝️ Ok, where the hell did we get `blog:posts` from? Well, this is called namespacing, and it works similarly to how importing stuff in Python works. We named our blog app's views "blog" in our root `urls.py` file, and we named our post list view "posts".

This means that when `redirect` gets the argument `"blog:posts"` it splits them at the colon, and looks for an app that's in the root `urls.py` file named "blog", and then a view named "posts" in whatever app was named "blog". Cool huh?

How does this help us? Well, now lets change the URL to our blog again:

```python
urlpatterns = [
    path('', include('home.urls'), name="home"), 
    path('thoughts/', include('blog.urls'), name="blog"),
    path('admin/', admin.site.urls), 
]
```

We make that change, deploy it to the our production server, and that's it. Because we didn't change the _name_ of the views, our redirect still works, even though the URLs are completely different. We only ever need to change things in one place, the `urls.py` file, and none of our users ever encounter an issue.

**Comment by KBiz65** [comment]
I had names but then didn't understand what they were doing so I deleted them. The guy didn't explain it on the Django tutorial so I wanted to see if it would break it by not having it but it didn't. Now I understand why though.
