### ISSUE TITLE
Remove "Replace Me" from base.html

### ISSUE THREAD

**Issue by nickcannariato** [KBiz65/kevinbisner-com#15]
https://github.com/KBiz65/kevinbisner-com/blob/1b2a309fc8a6dca644c57f808006b477a85ff546/home/templates/base.html#L17-L19

Not a huge deal, but if you ever forget to replace the  `content` block, or it fails to load for some reason, your users will see "Replace Me" rendered on the screen. Likely not a great experience.

**Comment by KBiz65** [comment]
Removed.
