### ISSUE TITLE
Handle URLs more appropriately

### ISSUE THREAD

**Issue by nickcannariato** [KBiz65/kevinbisner-com#6]
https://github.com/KBiz65/kevinbisner-com/blob/1b2a309fc8a6dca644c57f808006b477a85ff546/kbsite/urls.py#L26-L30

What you're doing here with your root `urls.py` file works, however it's more appropriate and scalable to create a `urls.py` file inside every Django app that we build, and then use the `include` method that `django.urls` provides us to add specific applications to the root router that you have here.

Since that paragraph might be a little confusing. You would accomplish this by first creating a `urls.py` file inside your `blog` app, and filling it with the following code:

```python
from django.urls import path

from .views import blog_detail_view


urlpatterns = [
    path('', blog_detail_view),
]
```

Then you would do the same for the `home` app, creating a `urls.py` file in that folder and adding the following code:

```python
from django.urls import path

from .views import home_view


urlpatterns = [
    path('', home_view),
]
```

Once that's done, you'll edit your root url file (the `kbsite/urls.py` file) to import the `include` function from `django.urls`

```python
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include # previously this just imported 'path', now we're also importing 'include'


urlpatterns = [
    # the include function takes a string that represents the django app name and 
    # the specific module you want to import that contains the apps URL configuration.
    # For example, if you named the file `banana.py` instead of `urls.py` you would
    # pass the string `'home.banana'` as the argument to the include function
    path('', include('home.urls')), 
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls), 
]

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
```

More information on how this works can be found here:
https://docs.djangoproject.com/en/3.0/topics/http/urls/#including-other-urlconfs

As far as _why_ you'd want to do this instead of doing it the way you've already done, the answer there is "scalability". You now know that any view you add to your blog app, it will always be behind the `blog/` path on the URL. Additionally, it means you only ever have to edit the `urls.py` file for the specific app you're adding a view to, which makes it possible for your application to be installed in any Django app and then "just work".

**Comment by KBiz65** [comment]
This one totally makes sense. I've updated/created my urls.py file and updated the main urls.py file in kbsite.
