### ISSUE TITLE
Remove the static urls addition 

### ISSUE THREAD

**Issue by nickcannariato** [KBiz65/kevinbisner-com#7]
https://github.com/KBiz65/kevinbisner-com/blob/1b2a309fc8a6dca644c57f808006b477a85ff546/kbsite/urls.py#L32-L33

Once we reconfigure our Static and Media files by closing issue #5, we'll be able to delete this `if condition` since whitenoise  will be handling that bit for us.

**Comment by KBiz65** [comment]
I'm keeping this as is until we reconfigure Static and Media files, correct?

**Comment by nickcannariato** [comment]
@KBiz65 Correct, this one stays until we reconfigure Static and Media files.
