### ISSUE TITLE
Delete unused / unneeded modules from the `home` app

### ISSUE THREAD

**Issue by nickcannariato** [KBiz65/kevinbisner-com#8]
If I'm understanding the purpose of the `home` app correctly, it's only ever going to be used to serve static template views like `home_view`.

This means you can delete `models.py`, `admin.py`, & `tests.py` modules from this app since you don't need them. It's only using `forms.py`, `apps.py`, `views.py`, and (after you close #7) `urls.py`.

Doing that will clean up the django app and make it's purpose more clear. 

Related, this is also why I was recommending naming this app "pages" instead of "home", since it's used to serve static template views, and you may want to have more than just a home page served by it in the future. Not a huge deal either way! Just wanted to mention it.

**Comment by KBiz65** [comment]
I've removed the non-used files and have moved my html files into a templates/home folder. However, now I'm getting the error that it says it can't find base.html (which I do an extends from in my home.html file).

**Comment by nickcannariato** [comment]
Yep! Because you moved it into a folder it's no longer found at "base.html", it's now found at "home/base.html". 

As a result, anywhere you _were_ using "base.html" you'll need up update it. 🙇

**Comment by KBiz65** [comment]
Found them. And then I had to also change navbar.html because that was now home/navbar.html.
