### ISSUE TITLE
Move templates into an `app_name/templates/app_name` directory structure

### ISSUE THREAD

**Issue by nickcannariato** [KBiz65/kevinbisner-com#9]
Currently, in your `home` application's `templates` directory, you have the `*.html` templates in the root templates folder.

https://github.com/KBiz65/kevinbisner-com/tree/master/home/templates

This definitely works as long as you (and also any developer who's package you're using) never ever name another django template the same name, but it's very likely that that's going to cause problems down the line.

As a result, a best practice is to create a directory _inside_ the `templates` directory that's inside your Django app, that way you can avoid potential conflicts and have a standardized naming scheme that makes it easier to name templates in the future. (after all, what to name things is among the top 3 hardest things in computer science).

This would mean that in your django project you want your apps to have a file structure that looks like so:

```
blog /
    templates /
        blog /
            whatever.html
home /
    templates /
        home / 
            whatever.html
```

Let me know if you have questions about this! It definitely took me a bit to understand how my templates were being compiled when I got started with Django.

**Comment by KBiz65** [comment]
This has been updated.
